language: node_js
node_js:
- '16'
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: Tag Develop
    if: branch IN (develop, master) AND type = push
    git:
      depth: false
    services:
    - docker
    script:
    - "./build/tag_code.sh"
  - stage: Bundle JS
    if: tag IS present
    language: node_js
    install:
    - npm install
    script:
    - npm run build
    - "./build/github_release.sh"
    deploy:
    - provider: s3
      access_key_id: AKIA2WMSJGXU3J5T27XB
      secret_access_key:
        secure: MWxsVyCwNb9/A+mMI3/5Fcgs/HnCisQ1tPXqoXYNiJnlOgQUzd3vbcOFTLm2zu4jKCgspctIv9/zuGPfU/Cgnj3x8mYk3CyKfsaWZ6Dq4DGXHLmxPjpyhheZoN609utnW56otv8pMNpFMsljlZ2nWjET4wNnD0TpxILY0cqvixVCv0Hv0MmjwWx+DMz4NHlKBApp3z7AE7fo052sdN+Z0PNOfJCQfpNlhg1M6b+9g+bDN0jYuLjBNSUw0p3UmBtitYJ8c/RiOrAgsKL6PG6A+8WF+XV/enapDaWL+wcFIrSfIlHMlZ+a5u5Em+DN8FbJfXDqiLBjhBh6yySO7WxzY1oQpyDVkwLFheQ5QjDjMmkwxFTK6cq12sAnwrp7vngadWKgt62Tstm1w2vczEDl7TZUqhrLw8AzVqEw5j5l+ZM+liOeXomYrzYVz/2oh3BunKTfA9mJ8meP1Zvb42PDxQAABHVOI5qArlIAdYLxhdBDONHTtXTU9FMGkn1qplQuEJavJdxrQf1tmiFhCZJiRDlLxMNAuOiuqbGBpm2XqG77L7LRxxIBns5dAcOLSprUVTVE/0r5v6nNSwTPx4TJ9GMOR4EaBVpLX0zR7iPg9BDSLZN7ho7cpRTeCix+NXBugm8UPZAP+N4sS7h6tFq6zZY/q4fkCtoJJGfahWPKNP8=
      bucket: span-presidium
      local-dir: dist
      upload-dir: presidium-js/$TRAVIS_TAG
      skip_cleanup: 'true'
      on:
        tags: true
env:
  global:
  - REPO=spandigital/presidium-js
  - secure: WkckwrxGLm1e7EqIpZsbq1/fhLxAHNN98gztsFA+MLhsYtogyF+QrbXj4K9lXU8ljfZLcX0m7iga4tgSz7WquD+bELz++JWtuKMAdPinBOv9Jinb6oLd3sBbszXJh0MRuRmrpZ+z8GBCX+Pnn/EzwPr94+4m9Jyu1AC2+Qbac8wcRftV20EW0c16DqOTLKgPpP/rfGz+z1oXMEDTsyEeyjp/qZZ+MKSBjiV+t/qTNdLxtIOkZmuCZqNkpfYJW3KAoY1poCB1HcBsBDlAxOsOAwcbM2Pmcf3fTWVCM3xnNPuMKWGiRz6IfX321lXR81kp1EhVczkRxEW4HY8k1mkeZDIbi/LUyq2XGdkMiKcnglIudDW5WGVJcZ6atvrrmVQc3yoLnhOrWYNdf+PFgnSnLLDEzRxqfdcyP0VdmnWjZVoYC4HmPIcvD5r9a53S3L8oAwSQzRXS9BYXnuOE6/cJ81qly7nHU/ZrbduKrzp9X/CHpYJahsY6Oh2PSWSBi2EnlyLKkdDH9qtyxeJ36acPnx0i5r9J9P4EaEEmkrgfb0p8chvlqsq2do3mtYqdgY3UpRh6bdfMt7kq2SAP0CiLe66tXHObCKeWOTNG/27OqOprw0AQCCoAuY5ASuiqhF9pAtcRqL3yoKWUwwAeBj9qSi5i+miA2qGIETnPBcDSLHM=

  
