language: node_js
node_js:
- '16'
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: Tag Develop
    if: branch IN (develop, master) AND type = push
    git:
      depth: false
    services:
    - docker
    script:
    - "./build/tag_code.sh"
  - stage: Bundle JS
    if: tag IS present
    language: node_js
    install:
    - npm install
    script:
    - npm run build
    - "./build/github_release.sh"
env:
  global:
  - REPO=spandigital/presidium-js
  # GITHUB_KEY
  - secure: m43SYbwjPNtLCov0epJTdUPEhMmL1m8A0qW782kxCD5rbuenvtNe/dFficpcBXKFwXlG/wAUIUMkkFtS5EON9Mz6I3lPr6Ux+4WMDH7fM30SsRrjI9CxTxlSn8avtGG2nGk12KNzriyhMBYY5pCRTsRkStqxi3zp5ZQaWRFBw1pu5vGEIwgtIQW/KYboQSqJ08+cRthiInq0laAUX+5XNI7fK1V8IwH8JmNuFHsPVbQnmvSh9g1sq0OGSfQatHjru6x8f9a4s/rQaWZ9YQhAyRHWV/yveszSvzwzUtX/VKfPEG9N2j2CLfbPf5HH2m4ah/n8ZpNOOPk457FMH1meG7hVmwZidf8sTnupUe6lHXV32YANLAyGTMMQh+ylYAHWq5/qhF7dl6SI/xuCd05mp7R6qHCqo/S7HoNOgW7fbRz2XDGaVNu1UWD6himgclXlgJc7oqRc61b2LrKRdh/JUlAFJqCQUTjZ8Oe/PMY9rGiEJ5BY6sZzxExT2DHhjq0jh2nqo7CmZ+1at87S0z/4B8f3lYGzYlVwwxx6YX8pZQbxrn/1bpMEXoTxnezFMGcDF6DChns8JB7xoOAIAm0sGGEL9z0ncRjhzS2u9pAphZ7QP8AxIHuzWjmaMf0MTW8HgEhp9i965yK39RP6FNO1U0Yb0kUvVTKkrZv+SNzuqE0=
