language: node_js
node_js:
- '16'
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: Tag Release
      if: (branch =~ /^(develop|main|feat\/.*)$/) AND type = push
      git:
        depth: false
      services:
        - docker
      script:
        - './build/tag_code.sh'
    - stage: Bundle JS
      if: tag IS present
      language: node_js
      install:
      - npm install
      script:
      - npm run build
      - "./build/github_release.sh"
env:
  global:
  - REPO=spandigital/presidium-js
  # GITHUB_KEY
  - secure: C8YJ/dMQwF858MJ1f/5sS9LoYGIcBivItz1nriAtxKDF9CzkKYiwok8yo9Ujlim+a/l6SK6c9o1RaUmIeZq+pcJh8VzQMFYvZehi+EcBjbRpRyp4LNztA6h/Ai45oplWmJyExefot6UcEcBEerxp3ZcAupQ3WbKsmUWNIng5wpa+ZPBeRRtZXU3cKI1BOYjUDTz6cE3h2OVwZbApFDrDQPZLUd3FXblX7z4hyVYBk3j1VuV1RrzWvebe/rAvpxF6Mo3fJH/iCS3ss4tLcVvvfCRt39SVlrHxUkpQQhusBpAKRMOOZrfRCf/U1vy9tzbC+f20VAg9lPEI0ybe19BY4eQ3IS8wwbouci5grORX0RPaYzypAv0mzGvkBqBY4M2a0xFVPldt6RyL19VS45LMogmx+eGuo8+uiKeXhhdWU+ILgd42OFZassGQ9mGnMW9X9xhhCbNIzOXkZjkLVx2PSRqeOnkFPjI6OD+rwM1lAnnco6Tu/AWRt+zi7iUqG7moMXtaYZhFSx+s6m5Ot0RcZKeNWKn15InksAWGjRzwen2eJAutdUoqEaSchc/tHiQlj0xAVmayWQlvQulKqPmt76vMtNag+WoHj5mEa0Pn5TXK9nFPHSae8taAwd0eGN/ExMDPxXycIYGbFoQ9P4K7zGjniNXPIqXl+facSscUIwc=
