language: node_js
node_js:
- '8'
cache:
  directories:
    - node_modules
install:
- npm install
- npm run build
script:
- mv dist/presidium.js dist/presidium-$TRAVIS_BRANCH.js
if: branch IN (master, develop) AND NOT type = pull_request
deploy:
  - provider: s3
    access_key_id: $S3_ACCESS_KEY
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: span-presidium
    local-dir: dist
    upload-dir: presidium-js
    region: us-east-2
    skip_cleanup: true
    on:
      repo: SPANDigital/presidium-js
      all_branches: true
      condition: "($TRAVIS_BRANCH = develop || $TRAVIS_BRANCH = master) && $TRAVIS_PULL_REQUEST = \"false\""
  - provider: npm
    email: presidium@spandigital.com
    api_key:
      secure: qVRDHdtXr/QEJ0VMuf9B1TaXjlCrtR89/h4Ks5TIdyv+Zl9VUlQduK3ybvaMfSVAr1RJ7521eE2x3cAo4VHgnbH9bW7Y29GAbdSZeNhfiPB7LnMBGF7QtHsRYZ2MPfPKt6sgURgpK+G0ZNBCLi056gpGYXcYUP0Q1sEc9UAfJXe4rIErL69guGFoMtY3mBcMSpPqTg7QkoiiqRDvxGthBAHGyTepJugmscgAjyBOXxh9JSnyKt+mj40WFu/j0iJGUsz7DXpjYkc2AV9+lPYG88WFwukLtMupKO7FsXuG+5bwEdz8ywprl9jTKCT2Fp6WARCiKtDWiskPjkOcAU42WrTw0qFlnhVTBU5FGVxt6ruQKdJBV6J6wfjxk7mzNeAR+1BYka1cPtZXBEasoXfxduBwcrpmHwHlgKNG7agESLmLXybz7TiBfFzFtdKAr4xpx0kzSn1qZif4d1q20DDB0I1fI/RdE0bmxVzrSd6+OS6zv+jqemv2ZuIFzfinD+msrdv2hAsTgIUfToOnwbZep8Sa6ys7gmA6awvYvnzbLFHHhAjaOr6ynERf3kyuTuAZ/KHeFhm/C6sfOzZ3nEHhU/4mp0JATyNlAuHfBSRQM3bI+hX3hnx4R8otmTtapkonq0eaugEqnKuWmbyR2QdQbVYqxkkIizzGAaJ8AdWt67s=
    on:
      tags: true
      repo: SPANDigital/presidium-js
      branch: master
env:
  global:
  - secure: jrqx1+fPqyx2vCZTE7H3qWmsSFDTOFaVwgej2TXQTceBv+Ms1JodnjptUHllUQqZy5tgxYB53lC1di8t3Z23J8mtFZneQSaeBLslo6thFTqhWeqSpa4vyfuBAY7st4IarXUMNkyP1GQlBMKZu+4YhyPcpGOchBuDcuvGwYPJEHvDR1EiO/jpRTzdImVreceU17l6d3Tq63Q40dwdEcMh/mALzYR2NrwvTFrrM7QI3FoD9t3lxj1mQdF9WrZcADyoxlpn39BfPF2OdfCySXwQdpYtsQegI0M1GqbnrxkJ0ZKrKFjOSDiGr2Oi8MFoJM9Wd52k7aovxhCCV9momsL/x/1bYXdDEQSgN3GHXcabQkgctR2m9Tokhe2luBAuE0ZFxOGL3kJplBfgWUhEcQPa7LGYK+k90DEzm+fQGByX3GjVAu1JgqEsZH/L04zVa7Kwb+t3fg1UjD+nE8Un4dRrFv9NBLub+ZHXWLN/SZXe+XW0iL9AOasSVV07VbCMW9tr0AEid+ZF2oJvUNJF05sYhFlUJA5taYCKTJih8orlE8ci+QvfOdmj3ANOMcW3eao+CDg9AB9Wc1zHKvnZsABR/0dLbPWj+TbPUxz8CjhoI8kzTKq3RTUbZjDU8o58Iqp+Iv3BATqRVySxlJAx5mYU59PrNgdd0R8POjXZWVWmKmg=
  - secure: ITyTmsTBQMRF98YbqQvDL7HtarJofD1B+CdBZBbTom7yU/0YIiIs1cw10S8KcVMxgkLdrUKtjeFBuSwQCht8zxCSI+tT5oiCS0joALFoLJW0mTtxjRZXpllHDX6e7HtuDiSHM9baFXRuFIyrXrnsbfwdRPz0NiIdD1MSoqtqwxBlAtaQWxRowL1NNKnYRV+ZPdiqORDx8kCoYQBsEdT0+hQK2wYFYACqXYGfVY9w1RM3diiXCCIVMKrpNK34CnwsKRTq/h+/IxQE/A+31M721HocfcXbShK9T1j/qa+z7JHcT3rNicTCl40+LhSdowAlAfw+pjSGYAZCE1VzB1zoBI3KV640kZY0Ocla8ZsjuEnEJME+jXxUG2JSO0FAr1uPuksYF1jXzdOSvOdNconvCyRicGDJaju49rh6Uk3VGmWqqklBpwgWxeKFFbdfRGmvM7HijvdGeWrrZVWxpiznzsX8UOBp3FKiiLdWcu43yqUbjZm2aQShX+drnyqZw/VVs3AHNYC0f/qRB4sRDdWUffPboR8I5WQcsClHs8B35FGZnT3jCuB8DF1KRqUE2VL9uJMyIFgs7E7iqFg/AHJAUGNkAilXairC9oaRjVB7PL5UwVtSQ+zIavhC/iCXi+tIfH2gc4Igq5z6cgg5ZGTke4ALZSLZaGG3th5r8BcHl7s=
