language: node_js
node_js:
- '8'
install: npm install
script: npm run build
deploy:
  provider: s3
  access_key_id:
    secure: ZWKQcmemFyAcIfotTwsqn2oTHKwU2OA3yoo8tLdyTwf9U2es8dfpIdI/b/hidYM2iiMftSMX3mVI58V1XjUoQVRdDRsNfRqvy+uempony3Px14gmoyhJdlfW4mMw+5qktaJhLOeu7Z3QhvdhnXTGg2GG6jVfgm9jgD9ZYYp1DBHlcJLpFA3ycpq+fmNkvt36WznkLWs9M17J3DSlX+x0R9LrZojndZ+caFM3Hh4+aqWGST6PLpD0YTKOw4XqA7XFxOBhTyRtkEActeK04Srp9AKLXCpqTrVcpzImyg/xXG7YEeaMBxo319sCFzjnsQCeyN1xxPVqF09zZL87GbN+asW/m1XGHsvyMFEeNwXyK/01PHO45vBEEvGAkkXnViUinniCfM77XMUQg0y8B0fJPb1agNbwdaHzwfnYFs+UpORRBlztWvUI88TyTyBqjOT587S6XV3BqndUIt2IrHXjgKTOrB98KpH0KWZ8XpFNaiO6Dk8YAjjA8/Mcp2/zEmwxmmGeTQ0UqaRgW57pwEGQYz7YgL15ir9YD+3riIKIYmFQAFA5/CXF3/yUfwWE+qC/0H4PJfl6GvXHZOVKojcH1QivHVv7Rt8SYJX1mpEK9fpeG8UFCHOZ9ueN3TX8RhZQQ2xuhVcpFNsVt8VRG2h1o4UzHH4uestyHuU41YMAf40=
  secret_access_key:
    secure: No9+ZVabogEJcTX3xfijKJB2g07f6IWZdq3EmuOJ3GuUdRnZ/bKxjQ/+bNxmOg9ZrCewzRnQIbR5UqNV3tQp2J2fb/m8gaNahDuvAiMJz1H+knGsP1gRUWDY+Afyr9pF3Hju21Q0xKFgPox9/2HDHitealKLZuAFEEuf8tPQGTtKnmp4VKyWmJMBAuWE/+8ILcW2//h8j8C18c/NgXVvD6LKxxitsbH7DUmlg2y2KQaGTkYsH0hhD9exF9tQY9OweNWScVhs8aDGxPmCbVA/h1Tly0QX+GWTgohsv21EvvBPPJns5Uugw8F0oYFKPgHSUDl4ggDceF17oSWIr2b9vbDKM9c6SbQhP4zLNBX1xfggm+cxzwGlXqladLOU+PD5UmbRWX3V7A8RBk3qf7UH0GW9xKMVn2Deo1SCTmB3rJP4LSyCMappD5qcWpVIchECmuiefiY13VoK1WdrtjauEz2Y003O6l3ZAOAEUUFo61qzCsk0fPIQD90gDgZkxs8uHOte2jpt+2CLt3qCIDJffzOQy4Q6PCp/qE9UAn6ln/vh17E13PiOX6iq7LRbC26/gS+kcMIHuuPgCdw6RfeNi7kMyep8Fsiyefmoa4IyUY0/d0D3YRPvLn3i6ubxyVpewq7dC8T/iCaguFDnAPRNXeJAE001boiSSnVBUfZew+A=
  bucket: span-presidium
  local-dir: dist
  upload-dir: presidium-js/develop
  skip_cleanup: true
  on:
    repo: SPANDigital/presidium-js
    branch: develop
