language: node_js
node_js:
- '18'
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: Tag Release
      if: (branch =~ /^(develop|main|feat\/.*)$/) AND type = push
      git:
        depth: false
      services:
        - docker
      script:
        - './build/tag_code.sh'
    - stage: Bundle JS
      if: tag IS present
      language: node_js
      install:
      - npm install
      script:
      - npm run build
      - npx semantic-release
env:
  global:
  - REPO=spandigital/presidium-js
  # GITHUB_TOKEN
  - secure: YQqqK4k1ihPSlRzn86eXN5yCG/AYK933guTkvdwKz/HabTDVIjoV5VdtbKc+J4MtVA00pex65mIT3/e/JpRgOCj2cqn4SzYC9vuB52I/qH8l4xYmKWZHfnQd21i94nQsK2MoZP0YJXY7tD5oveTTnAceeMZqemsNGlXvrl1IajzyYDcWpmhZlKbHodMTZ6Dom51UWbNqI0tspbif4IVkbOLQSUSM42Iaes8Zly1jz3BS93plQsqfrT4ER84cwAZ1SZd4pfQJleGtGbF+tfSGB4l/BWaY4SMeO7tgZOsEogu9WtroSweShDCJoLnVdMz4+OptjzN/ZhMzjIW0euTfw4FueV4/rzUVzEKeTZ/5uH+n334CFldBBIj+GDwb7L74pXKL0npEFDaeoZhnJ8EpKLHBVIhelU2ce81LaL6UFxAIH0KDnLXEhFtM3ZCWUIXpcKHQ65GRVFsWxssy1/vhV+CynoNA3aw+Pd7b0xA/yNIxdr3xUpBmW92TX5IDRYc61B9adGVNQt8+muox2Cb38ZngFud5JY0cBeVmU23mPmHsXXYy05PzTVqKRwwJEQwboIFWVNe+Ot5n4VIKDYEbSdyH3BKJbUQNj2UBzRnVbXNJDYci/74/qmvqPR+4RGspAnzOwncffOgqKsipKQ9y2vaiI8sB6WVSidQFjuWjkbA=
