language: node_js
node_js:
- '16'
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: Tag Release
      if: (branch =~ /^(develop|master|main|feat\/.*)$/) AND type = push
      git:
        depth: false
      services:
        - docker
      script:
        - './build/tag_code.sh'
    - stage: Bundle JS
      if: tag IS present
      language: node_js
      install:
      - npm install
      script:
      - npm run build
      - "./build/github_release.sh"
env:
  global:
  - REPO=spandigital/presidium-js
  # GITHUB_KEY
  - secure: b2iwEawiQ4JEHYKWtR+p3GWXcC3QH6Y0pGa45IE5eGQjWFWXN8wgtHhQMe2qjM+7XyLcPThEXiHa/krDu/TRhz/GBGUR+hq9bsk2joyu11nAQ0B39sqzimBfR48IarqI0mRb07F4SJKZPKvX/SNSJ38NdAMIcYK+o6Cu4gsjYm7zCTVDHDEyjJbiuTq+Zts7xUq+8aHnbX5SX9AIIn3TNcZ3WP7mnM0a6HSZd2/TAG458W6LckjhlYAWtZLD18W2ZhN8VDy5XV9FE5n6r8wxAu4u4G4HSuR1IoryYHvR0M8ILSmxUxBxW06GIS+F5kLyD5Hvf+UqcOSiJnr0KL8jOV5m5MmNbFIW/T7VVb9mSzrdSKK5qf2VB1MHtaDFrtbiwxEk0/QHnNTcq3HYjVHFFU7cTKMcuzQo7ivxlOK7LvbsB9OxsAyZvPnZSIhFFFCCY8k995+suoTwYWDafn+d/EDGFq4J4ekf+YdzVdgFlg/o+UJEl4h/B3rOpF4eAxsnbZQrj60uxvas3VfSqfFBp/Z4I/mmZoOxJcW28//50VntqKR3P3R/N+IEhFWH6n8dNKhdGdhbcAy/ZxTbV9lbORLxnXd7jUxXRHNLQSbYNuR9o0CKWtaUWg6fPvIYHfNGZ3Bo+JV1U5ARNpTMmd0fLWcNIfhaiR10Up1aSVWfCMA=
