language: node_js
node_js:
- '16'
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: Tag Develop
    if: branch IN (develop, master, feat/PRS-2341-deploy) AND type = push
    git:
      depth: false
    services:
    - docker
    script:
    - "./build/tag_code.sh"
  - stage: Bundle JS
    if: tag IS present
    language: node_js
    install:
    - npm install
    script:
    - npm run build
    - "./build/github_release.sh"
    deploy:
    - provider: s3
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
      bucket: span-presidium
      local_dir: dist
      upload-dir: presidium-js/$TRAVIS_TAG
      skip_cleanup: true
      region: us-east-2
      on:
        tags: true
env:
  global:
  - REPO=spandigital/presidium-js
  - secure: n15138Z7GN7UYHHYf4n3nshBrN1s7B0+puKRdgTHeaHVs1LGEyvXNtVI1vjS6hXEfjspFa7c3ZnY8rLXkOpoCg/1GMuaC5i9ywytQ2HHp8LcPG9ONiFAn9wBGH1knhSX6c4TKaqSOiT5RgEMw3JfS6bl5tXu/vDGpuV+6dW1JvLzV1taDab80asDEQR2i18El516yutv/pKNV8nPYn2MP6pL9s2t56aq+eEgmYcbaF7/m4rkjNExzTe29huyj0K66hEMfk+/wlBLkd8mLL6rtXg9f3n90fTM3F2qH/YXvKw169GJQEm7IB1MUUNhBYbs7OVxgm0mxcWu3XHXyIGj4EwfbcLICJ8sPY1K9CtY0im2vXToBlpK7Ioynt/E0SuG59NQGL83rHpJ7jF3Wqx4S11UKktuZGGE1faN0x0DmUCBPHwCmn0efxrl1UVCmKsBWsWL56KPgsnjYqsD7lOhoBZq1JK57HyRyl22TSlKiU1Pr/Yv7PsSSKROXVJ6TqbqzyzFS23NtxecBMP8qyAEHc/4wNGh2UhUksIXQGwIii9zQ+4og/zVFM68teKoRfEOQg6SdwbrqxLyvRGnkjQMgfI1wIyRXPhwUOTXMReWJqIgetFVtYbGGboSVghxk6Z4WpP5O4ymoGiC2ks6Sik+91PxYXAaDjVXRaCAkP2R1EI=
  - secure: Pc60Xqt2a0QQLHg+J2zgItqNjiTd4bCdk8yPcWRaU4e5eh7aHPTvI4R/+1XFcp5LaXBwxGSCS6G77nE71qsn0QAyv6EaiNSkyWblxoXoZB9IkrbvXEi0+nKNpjGcThokpEqgnOW4c8OlN3TlGeSMhMe+E7pqoig7Tu8YgXfym7/sBupRZ7d/8e3kZaDKAEd7T/Y/h7LsSVuz5imo5bNm0rtzgTffWqpOFWY5JbO/yoRrau1f7W4ZoX0M36sciYyM6/6byAebUFFvOQFiNhrhgwifBQT0snrT45nlqPFjXY6Y6ZdQ+Sb/1yUOcUpXXHa+VJr9VBQjyDuo50HiWYAQWOd0TdQ+Tt/bs9adGR3LeFrjTDHbumuUzbRtl5mZZ9NEkRtVDUEZTPtTmO8N1oWpSUgUrSehG0JE83E6Jaqh7ndjWpvyltRQBSIz3Z4cNLLP9dPtWIXdJ8WAtgIvHKenHXcSP0eysXPOXletqAZnNQEbpw/slAIIZ/TY2tujWZmSenRkh3CBOro2m6QEDt7wObJt4Oh94uPOzJazu07sQdEJWrDZTkfn/C/EaMBikdS764Un7H6VjKgjEdl5Y6K/xFRwv8caRnTmTgUHaHUHW50cttXTtsU3kBY8iGIjutry+YIzYHklmG7J+3N5bObJ10aG2sdzuiCp58IC7xJlxR4=
  - secure: prBcYFoWuwC9oGA8fD8wXnVNVEv7YzCA41fwuY0x+GlnqRjb/a5SlBCcACuAjB2sD6yJfFq9vF5GcP42Fbf1O1kTEUxDV80l0dYaGwOtzFCDlfitgzGBalY39ddK+QNtGrJRrsk4wU3C1YEkthiFOe1BbOSj/P+nYyIEXcOnHbRS6LAkq2R3b7sTtnLuxT1+HetbHpu7EKa7EDb+YE+pMyy2LbCggFlbtnx++izfd/NaMLu7fyDURVUeyKEzINc3yPTXvoZIUu9VqVVFmcwgEs2pzJbl94sjaD/G1iB2m1I8dqrkNn67CgCbNc/cirGRzYm7nxSLqCELlfBE/bcQDLrEvAeiJ/CzEOyNuNFCnNdSIOp38bLbIdsw04YRYf4HwiTv1VrHHwCPrBGoPRyAO7fN/4qp9GW2PngNpOnV2c/wzG0Q759s254bdXw0tccir4a3/rD0/bXowt2P/luLA8nmgBzz70/ccMWSJXiU9F6ivPgjB+KwfkbzOjUUhezplS8vt7U8BsHal9Q5hxgQV0wSNpuwpnLhbdeVmlR0rLbzzd3ISawZY2YPkNGvQjSoanE9AbhIBB0WqvFJC3UkHo1kJJu6LdIr9/YVet9HpSB79D3yEO4rbcTtINUwT+aE61Kq/b/8NMbq4qCy4bR9ioPjv9clSiAtWc9sYtSZEnw=

