language: node_js
node_js:
- '8'
cache:
  directories:
    - node_modules
install:
- npm install
- npm run build
script:
- mv dist/presidium.js dist/presidium-$TRAVIS_BRANCH.js
if: branch IN (master, develop) AND NOT type = pull_request
deploy:
  - provider: s3
    access_key_id: $S3_ACCESS_KEY
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: span-presidium
    local-dir: dist
    upload-dir: presidium-js
    region: us-east-2
    skip_cleanup: true
    on:
      repo: SPANDigital/presidium-js
      all_branches: true
      condition: "($TRAVIS_BRANCH = develop || $TRAVIS_BRANCH = master) && $TRAVIS_PULL_REQUEST = \"false\""
  - provider: npm
    email: presidium@spandigital.com
    api_key:
      secure: qVRDHdtXr/QEJ0VMuf9B1TaXjlCrtR89/h4Ks5TIdyv+Zl9VUlQduK3ybvaMfSVAr1RJ7521eE2x3cAo4VHgnbH9bW7Y29GAbdSZeNhfiPB7LnMBGF7QtHsRYZ2MPfPKt6sgURgpK+G0ZNBCLi056gpGYXcYUP0Q1sEc9UAfJXe4rIErL69guGFoMtY3mBcMSpPqTg7QkoiiqRDvxGthBAHGyTepJugmscgAjyBOXxh9JSnyKt+mj40WFu/j0iJGUsz7DXpjYkc2AV9+lPYG88WFwukLtMupKO7FsXuG+5bwEdz8ywprl9jTKCT2Fp6WARCiKtDWiskPjkOcAU42WrTw0qFlnhVTBU5FGVxt6ruQKdJBV6J6wfjxk7mzNeAR+1BYka1cPtZXBEasoXfxduBwcrpmHwHlgKNG7agESLmLXybz7TiBfFzFtdKAr4xpx0kzSn1qZif4d1q20DDB0I1fI/RdE0bmxVzrSd6+OS6zv+jqemv2ZuIFzfinD+msrdv2hAsTgIUfToOnwbZep8Sa6ys7gmA6awvYvnzbLFHHhAjaOr6ynERf3kyuTuAZ/KHeFhm/C6sfOzZ3nEHhU/4mp0JATyNlAuHfBSRQM3bI+hX3hnx4R8otmTtapkonq0eaugEqnKuWmbyR2QdQbVYqxkkIizzGAaJ8AdWt67s=
    on:
      tags: true
      repo: SPANDigital/presidium-js
      branch: master
env:
  global:
  - secure: lMlxh/36CANEGFYqnZRyBBJ40FKGhcTqbrM1M0zjAV2WUS43t8wkVriBJpOyb8ouvLpufffbSspvIMFf4kH9qz0MM/lrkmtPds+2xI0uIpvE2VhyuTwMYkw3o5jOevwX/4G+EB4MgHyZdMW7Sb0xMgxbnDgdavurI5iZ9R4jaEgeE3tpPlQEP5/Wo3ivpC+sNBTq3kYmkdrd83YrXB/NvL3s924A7Hc3hAfH25wyJZiM/uK8xcYOQjVPV6CtfIxdSmfi+mG08KO23BfkmvelIpfeXQU1lzAZwKUgOc+/i8EhDXgbfWVuwZyN4+aGQJG64+IK1FxK348eTQQFw4zRCftS+Qr9iZ7b36TsSudQwowMintmH1G4oxHgYPeeb2F1OdztoWOhu9TM/kL8g6v/cbiYJm3ddnOwK5e0QPY36q7ppS2U+vK1jjcUT61ilB8NWRLG3hNCiTcyE5Xmp5SBaV+eTZxc73+QX5BghjoNEAwO9+o/FjPp8G3Z9ziJc0RqmtaX+2TSeMbnQCPzcFwu1ra3hmjs4MWhpOO3C8zFpUinllrfrhyvEaFKxdMhmw4JmOf+I7CbwB9kIee9gHi3BSItzAr0wAJp6whhuGw0zgF59l1CaGuZPvBY8oBYNEEguPsIFoZjvcJ9qZ7q/cvAFYYW6EVRaRwDFEQb4BTBu70=
  - secure: skNdPjxtWts0gEMIWODBZA4Mo2PPpgo03yHSoFZfaDlJjezLnl7y4ZLIQ0VF2INYcC4CTRZ6DPvgkO3XHYM0oihBWE0NJ5n6IgSR/cJIu+NO/bJNSlgmW17REPhMCTEiERIBbz+M8u5kgUtpIiaG0ocyYS7R5+0JmXAqSJR1Y1/QSLxQK7YGHFpWH7R33UJOPhWD1Mc019CSqsVIrgaObpMYSl9FNGm2EHZsovmiDvnOYKwXNi/R7xNigT3t/eeNeAOSofjl2+o+52oADu74culfx8Kct/cWABqJeCGqg1uqhgRtyG1z1uBKVeflX/yjrmITlKsEUmyMt5TSV9LjiYjyDl9ODQZxBSDvi8b5z/OgQBmG/CVXp2ILLKzbQwjBjzoD3Alz86PAKfN/mQC4J9ZxnI5uzrWj6R6yPwfjZgkg23Hn7uTJfkgNLdx7NPqF2Za2OEpPuOh78CgUJ7l0acgWWb91I8DzRR4XeqbAsj8054/nDXacV1Hf8s5DmoXU+dl3P6SZmXAEBm3op+RRxzHJ90tRimxu71ACB9CFdSggXQibHlE5h8saArtP2nnKMQ310MI/oVvtPIV+iQfJ29ePE46Ru6x3L5Z7aeAIuUPyx1aAm2ZjabKgrI9blcJ2MfGks9RA9HpgQ2gDKZsmV/rIZSDKnJzdZ5AZbz9wuuY=
