name: build-and-release
on:
  push:
    branches:
      - develop
      - main
      - PRSDM-5464-setup-semantic-release-for-other-repos
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
      
      - name: Upload dist dir
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1
    
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download a dist dir
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Setup Node.js for Semantic Release
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Semantic Release
        run: npm install semantic-release

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run
