name: "Lint PR Title"

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
permissions:
  pull-requests: read
  contents: read
  packages: read
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
